INSERT INTO product_categories (name) VALUES
('Tools'),
('Adhesive & Silicon'),
('Paint');

insert into products (name, cost, url, category_id, initial_quantity) values ('Portable Electric Fan', 642.81, 'exblog.jp', 3, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Pet Tracking Collar', 501.24, 'g.co', 2, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Rechargeable Laptop Battery Pack', 376.77, 'msn.com', 2, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Dishwasher Safe Cutting Board', 853.67, 'bbb.org', 1, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Luxury Bath Robe', 719.53, 'dmoz.org', 2, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Rolling Cooler', 115.63, 'hc360.com', 1, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Almond Quinoa Salad', 616.09, 'house.gov', null, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('LED Christmas Lights', 301.05, 'nih.gov', 1, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Insulated Sport Tumbler', 866.72, 'nydailynews.com', 3, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Almond Butter Cookies', 888.14, '163.com', 3, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Mango Chili Salsa', 658.26, 'wordpress.org', null, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Asian Salad Mix', 417.22, 'pcworld.com', 2, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Outdoor Adventure Backpack', 865.32, 'reuters.com', 1, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Andouille Sausage', 337.32, 'ft.com', 1, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Portable Hammock with Stand', 656.59, 'naver.com', 2, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Butternut Squash Ravioli', 764.43, 'hp.com', 2, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Potato Wedge Seasoning', 333.15, 'pen.io', 2, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Leather Notebook Cover', 800.64, 'unicef.org', 3, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Apple Juice', 304.09, '4shared.com', 2, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Creamy Spinach Dip', 978.94, 'github.com', 2, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Chocolate Hazelnut Granola', 839.32, 'rakuten.co.jp', 1, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Greek Feta Cheese', 128.87, 'ifeng.com', 1, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Spicy Tuna Rolls', 88.28, 'tinyurl.com', 1, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Organic Chia Seeds', 477.51, 'exblog.jp', 1, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Nut Mix', 697.48, 'ustream.tv', 3, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Reversible Swimming Pool Lounger', 272.21, 'indiegogo.com', null, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Sesame Noodles', 178.49, 'vkontakte.ru', null, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Spicy Beef Taco Mix', 557.41, 'gravatar.com', 1, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Ceramic Bakeware Set', 578.55, 'vinaora.com', 1, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Grilled Vegetable Medley', 397.4, 'hibu.com', null, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Cotton Quilted Throw Blanket', 499.55, 'yolasite.com', 2, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Honey Sriracha Chicken Bites', 10.34, null, 1, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('High-Quality Yoga Mat', 997.55, 'naver.com', 2, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Wrap Front Midi Skirt', 3.16, 'topsy.com', 1, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Sweet Potatoes (organic)', 745.85, 'bravesites.com', 1, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Caribbean Jerk Marinade', 487.83, 'walmart.com', 3, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Portable USB-C Monitor', 230.86, null, null, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Dark Chocolate Covered Almonds', 976.64, 'friendfeed.com', 1, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Smart Thermostat with Wi-Fi', 517.68, null, 1, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Wild Rice Pilaf', 67.31, 'tuttocitta.it', 1, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Coconut Flakes', 258.52, 'domainmarket.com', 2, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Mixed Berry Smoothie Pack', 326.19, 'howstuffworks.com', 3, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Laptop Sleeve', 219.86, 'tumblr.com', 3, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Peanut Butter Granola', 274.59, 'webeden.co.uk', 2, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Frozen Mixed Berries', 229.14, 'intel.com', 3, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Sweet Potato Tots', 822.57, 'hc360.com', 3, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Almond Flour', 728.99, null, 3, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Frozen Hash Browns', 2.4, 'tuttocitta.it', 3, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('LED Table Lamp', 394.46, 'kickstarter.com', 1, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Herbed Couscous', 324.18, 'amazon.com', 3, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Shatterproof Wine Glasses', 673.93, 'tripod.com', 3, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Plant-Based Meal Prep Containers', 771.07, 'photobucket.com', 1, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('High-Quality Yoga Mat', 501.25, 'spotify.com', null, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Ginger Turmeric Shots', 126.7, 'japanpost.jp', 2, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Glass Food Containers', 589.73, null, 2, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Snack Container Set', 807.74, 'wikimedia.org', 3, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Honey Glazed Carrots', 13.62, null, 1, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Asian Salad Mix', 414.95, 'jalbum.net', 1, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Baking Soda', 492.64, 'sogou.com', null, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Kids'' Learning Tablet', 784.13, '163.com', 3, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Pistachios', 344.85, 'moonfruit.com', 1, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Backpacking Tent', 473.24, 'google.ru', 1, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Sour Cream', 757.68, 'npr.org', null, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Herbed Goat Cheese', 940.73, null, 3, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Veggie Chips Variety Pack', 756.47, 'ehow.com', 3, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Handcrafted Wooden Coasters', 382.84, 'squidoo.com', 1, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Ranch Dressing', 670.03, 'netvibes.com', 3, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Fruit and Nut Medley', 455.05, 'independent.co.uk', 1, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Vegetable Pizza Rolls', 748.31, 'oakley.com', 1, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Chocolate Chip Muffins', 988.52, 'mit.edu', 2, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Wireless Security Camera', 442.95, null, 2, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Vegan Mac & Cheese', 156.13, null, 3, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Ceramic Cookware Set', 835.36, 'tamu.edu', null, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Kale and Quinoa Salad', 882.51, 'hubpages.com', 2, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Beef Stroganoff Meal Kit', 69.52, 'cpanel.net', 2, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Cucumber', 463.67, null, 1, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Portable Blender', 493.87, 'posterous.com', 3, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Hot Salsa', 595.69, 'sun.com', 3, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Yoga Blocks', 225.63, 'jimdo.com', 1, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Sous Vide Cooker', 455.77, 'eventbrite.com', 1, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Pasta (Linguine)', 20.31, 'amazonaws.com', 1, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Leek and Potato Soup', 183.17, 'usatoday.com', 1, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Coconut Chia Pudding', 770.19, 'etsy.com', 3, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Smartphone Car Mount with Wireless Charging', 348.28, 'mapquest.com', 1, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Wireless Gaming Mouse', 673.95, 'umn.edu', 2, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Laundry Detergent', 913.07, 'jimdo.com', 1, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Maple Bacon Jerky', 932.91, 'amazon.co.uk', 3, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Athletic Sports Bra', 525.19, 'chicagotribune.com', 3, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Kids'' Learning Tablet', 992.75, null, 3, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Organic Spinach', 239.74, 'nydailynews.com', 1, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Electric Milk Frother', 396.33, 'narod.ru', 1, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Elderberry Syrup', 802.15, 'unesco.org', 1, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Chicken Broth', 793.46, null, 1, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Chipotle Black Bean Burger', 310.29, 'npr.org', 3, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Vacuum Sealer Machine', 720.5, 'google.fr', null, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Car Sunshade', 316.66, 'mapquest.com', null, 2);
insert into products (name, cost, url, category_id, initial_quantity) values ('Chia Seed Pudding', 930.92, 'mashable.com', 1, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Couscous Mix', 287.18, 'yale.edu', 3, 1);
insert into products (name, cost, url, category_id, initial_quantity) values ('Vegetable Stir Fry Mix', 361.57, 'so-net.ne.jp', 3, 3);
insert into products (name, cost, url, category_id, initial_quantity) values ('Vegetable Potstickers', 718.42, 'fastcompany.com', 3, 3);
